### ISSUE TITLE
Can you help me show that the kernel you design is valid?

### ISSUE THREAD

**Issue by yongchanghao** [yaohungt/TransformerDissection#1]
In sec. 2.3 of your paper, you mentioned that:

> we present a new form of attention with a kernel that is (1) **valid** and (2)..". 

Specifically, you mean K(x, y; W) = exp( <x W, y W> / sqrt d) is a valid kernel. 
It's obvious that this kernel function is symmetric, but I can't find a intuitive way to show it is postive semi-definite. Can you help me with this? Thank you.

**Comment by yaohungt** [comment]
It is actually by definition. The symmetric kernel is positive-definite
